# Generated by Django 4.2.11 on 2024-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='nationalId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
